# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# >- # this means to ignore newlines until "baseurl:"

title: Dom's Blog
author: 
  name: Domenic Gosein
  #email: your-email@example.com
# logo: 
tagline: Software engineering, work and life
description: A blog dedicated to software engineering, work and life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gosein.de" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: dogosein
  card: summary
twitter_username: dogosein # are both necessary?
github_username: goseind
google_site_verification: 6yjgiiATzCxUkZ0On5KXtnml3PEPps0L4Lo_RtUq3YY

# Build settings
remote_theme: jekyll/minima # set up remote_theme instead of explicitly setting the theme version in the Gemfile
minima:
  skin: auto
  social_links:
    - { platform: github,  user_url: "https://github.com/goseind" }
    - { platform: twitter, user_url: "https://twitter.com/dogosein" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/goseind/" }
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-gist

permalink: /:title:output_ext

# Excerpts settings
show_excerpts: true
excerpt_separator: <!--more-->

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
